language: node_js
sudo: required
warnings_are_errors: true

node_js:
    - "0.12"

before_install:
    - sudo rm -rf /usr/local/phantomjs
    - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
    - tar xjf phantomjs-1.9.7-linux-x86_64.tar.bz2
    - sudo mv phantomjs-1.9.7-linux-x86_64 /usr/local/phantomjs

before_script:
    - npm install -g gulp

script:
    - gulp release

notifications:
  email:
    on_success: change
    on_failure: change