language: node_js
sudo: required
warnings_are_errors: true

node_js:
    - "0.12"

install:
    - npm install
    #added for Coveralls.io integration
    - npm install -g jscoverage
    - npm install coveralls --save-dev
    - npm install mocha-lcov-reporter --save-dev

script:
    - gulp release

after_success:
    - jscoverage lib lib-cov
    - gulp test-coveralls | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_success: change
    on_failure: change
