language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script:
  - bundle exec htmlproofer index.html --only-4xx --check-html
env:
- global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: s3
  access_key_id:
    secure: UYjcZHhZmb5IKKCSOuc4WyftjiBoIlWDM2vMmS/udQHhZqumQrRgzVAxQ1c8ZtAZoWwXdMIKVFLsC+z5PMrI1jL7fujJAPuxtVsQGvZPrtxFqZydDHU3N2/tiGQ6yiVOccz1N8p0uFeaSHJKhYmD+jpPGb3D4FIXxcdy3TfzWm5JEIDC5Mo449qSqkohThaAQP6pzuS4YXQs/RaKptwVI7dQK3SfGeVDODZAVdQH/QJO43Qb4ovoSkOWSLJoI/sqF8eNryafi2lw0xb8D5sUHpZ433Nft2Tfbw5XRoNBDKhqevtCLVelUd2OQIZnOCvdczwiI+xrKymNmDPhdjjgGWoQfL3YRFs/G3u8bWR5dVcs0G5IDDBfa0XWPDwPsy5o++HSU8im9wHZbsvpxIY2TO3GPDoBxYALNW4HhMvd0Ay0qICsiLQv2sp/HxuLoyHpH/cTGCTRo9V3U2D4K95ioca4pLl0xn4l7fMxhaL/7+Uk6XLiKHlnYSPifR7tInR3iK4/nkqcunNCUfpnvgwenmdnlLDRhTSM8CKkaeICKPP8v0jyerV+VEDxYDqecD1SE8z4hgBGnsDcsyXQz/Hqhn3/PSkfaWI/BaujFTGkGOnR2I5yD+q2+UZofqrB5OsxkJz8bqejFg7PLNq7pi2pZlPWCzUe/lw/gtcvuI3ifPg=
  secret_access_key:
    secure: OrVLZsA9AKf//ZdGVcRvNrm+tANYBuZ1wvkx273zhqtEUcbF6K2mgOAKT6ybPjrOOXHUrIxIHrBUD4+sf9ItJnfYO3ezLmORfH14WqeiJYQEH9WgmWUS7LJldtEbH3mYx5zniF2y8EKcfRmm9OuNHIgI9CzCVZkh5mt2zERjheOmBehYVWt4cVwOW16dIjXKZQKCo2NEKLvitRGuOvCipClQvQVn4ki5J9fj509iQbhWbvQg5ha1O97xneibHeoXBt9Oz07UDFXuJQ+HmvzSeTFo/TRt2CFkCXsQYXeLRxLegFmpFuHBWMrzmcO+0bROuqai6RUJUQ3NdHWOdwMVvRdhPJUaPSq6qAKec1GXnkEi2yvaV/Pm3ljd20c8zkdfnk5WYiEMwmbRV+A9/pZEVHnnDEYZdDOmbZ+p4a7J4b2f0BJIfbA9ZjQpiBA/FZ1aWiSJHiPGRJ768I4Es8EWp2kN9kq3gd73yRzuu1VT+jJWw2h4oJKZ2brw81tjXXGe5GKqQwINf1jj1999PLfFZ339Gq/MrIV9i8tJxaUA4GXP/zBQG5YmMM7DHJulMhgAX4UKqCm9ZtYMvWSBVfPYPoFD/zRnf+iHTnI6/hlfxjU7hwgpk+Iia7ruTcpdioyAXZN9cjc9fBSINUwcLTEt/4Lp9fKjTzlN7aoDKRhIVqE=
  skip_cleanup: true
  bucket: opengrid.io
  region: us-west-2
  on:
    repo: Chicago/opengrid
    branch: opengrid.io