language: node_js
sudo: required
warnings_are_errors: true

node_js:
    - "0.12"

before_script:
    - npm install -g gulp

script:
    - gulp release

notifications:
  email:
    on_success: change
    on_failure: change