language: ruby
sudo: required
warnings_are_errors: true
rvm:
- 2.1
script:
- bundle exec htmlproofer index.html --only-4xx --check-html
env:
- global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: s3
  access_key_id: AKIAJODHIGA544MQYMNA
  secret_access_key:
    secure: vR6vA/4d7ZLFq3nhJbK4OBjjqDV+VVZQCW8PokkORil5iO2QPQ+/5wq1ZW6iNO9rkYg+32f9bbpqedxN8qFa/m3v+SYAyizWaZLA4N89GWb63Vtdz/E67Cr+fUkotar4HEOC+JGpg2LUktNDGLkyBpZO+gSs0CvJRkbZ+ZjxVvPcbLSQ6gB1YomEr/sqooYsaLRNJpTINsD+xeWN+yRA7e+4QLS36hwqK34ST+QOaZAQBG0Fbzu3LgdMUYEQi3lxLdtB7YOBJ2WVxiwya7Pgh7x0uspkCuWDFdwCTFo7Shyba7FwjMqUmswBp97g7liEnF99KR6fny/EVR6xzRlTQ3SU0MYxDKh88tKJbhmOeLo7iEWXTc3crFIFu7gIlDIfe3bkchp5C4cW9+Nr3och96kOsXmTYm2NllqEi4HsFOBb0OGU7/DsNTv+mEO2jtMv7gYvdDq+uTTKfj4hA39KnMC8/cE6avDac59FhrGNnlcRIOx91lMnd3TNwdiL6n72oR/g3e2IUrnBM6DDwDXdDdx+3E291xnJ0OobnDFnkghtCGNMqGLqO9gLkubZfrTWE/7PbKtJFxDpNq21eApVka1OOKoAH97u+urwrXauP1kTiq+Qm2x8sEEG+8ivnqnQ/AlWElIpJYehW4BPwZrOkl1O2i1QLTjJ70FZw8yoR7c=
  skip_cleanup: true
  bucket: opengrid.io
  region: us-west-2
  on:
    repo: Chicago/opengrid
    branch: opengrid.io
