language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script:
  - bundle exec htmlproofer index.html --only-4xx --check-html
env:
- global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: s3
  access_key_id:
    secure: jcXSJQbgo2h4BPXg0Xxpfk2E/AQVoC6Tp0KI1Zbq4uZYOrIkztwAd6MPjN8vRZcTOvkID+oQmq2JzurkIBeybwc/Zcm2jE11mSoOPCCqJeK2wDhPHOnRqU3fa8yarM9jZYN5uOYs5984+9hLt6kQc58T9wgEGKwLbl6QyKjq7ndhzfFiHQBASjVO18z5Jc9lbz0hxMll+Fzl6Rgrp57ew0Jh3txB5Oh+CYaZgUJGQQFbrL2AVwyE1gnnGAdT7XjKWIWOaGb4rW690cey5wbLBnMN8tCdMSzo8KNbJsJQYodthkgiYgr7zmzEhwd0Mr5tpg8FaI0XnbZgQMfFD9X5MoCVBu2XwV5ly+3pKfEGVxE4HXxmZI9OjKImKlzt3YGQQ3m5AvJXdbkLRwP803+9Ojwngxn41eqemqhK+wNtSPr8Oq/vHLh4PNbyzrWIl2OYUex531FmUXqubh9XxHtlgtyD3sc0GYTD0WOULiDlcy8QCI3Dp8hsiq35PKVBYlWRS+C6y6JluUaHHfYf/awfbmmXwCAnnPPeX7s4/Pa2IfhL8rFSIMfDXg/sM8vgIQvZWdvw43shHWJg1pfczZ/+a+B/WckH+ioNM6JYAlydwTC+IZCvkzqjgdVpBer/L22eCZfiDp2vx5MQplCTQ6qs7IfccGl6JHKdXtwsVWf4Rqc=
  secret_access_key:
    secure: j+5KV/GnQ2K+eCbuiUdYsBbYPPMOJopIqBYg6xsR+viRwlb/2nYEGNshpeK4CGCL6dgj16eYyGos/GKj2MJSpVPNe26fpBk37hhZzRu4ycq+CIa4nWyJhaHyw9Bn3aJbnD9mdSwBxXJ9WObIK06YhpbjQpKB3DQYHNbuk99Lus/ZSpCZvHq5IKhSLhZoJCi6EQEAv9ZPQ86CeukeKawmGfW5veKXfzyyjaomlfd3i25u7uES4YRdJsLKVJEzGBAXrpbeqttSWV549SP+c+kJsrI4ysiwmguyFBty/SAaNRLDXXsfBJ6ptiNaFz29CcjXCQRNWxjr8vi6tPGcTiY1sgSviT4uGQukTugcW3NhgBTD5yRrJNw3tK+z1JqCj0g1nJScwg5ELu4HENCTcFul5y131zvAzBvUaP/qcoGUU8YVQvrFbaBkpvxK3XJpP0TVv3tXXZjzRg7JEEBaTqqw+ear2Zeywtot9fWv3jLIYserLhtYuRLQ91VOiE+vMyP58hXP+jZTtxEDrBkgRWmes2wakGyxHUHmYy9u79G1lxQDodSmgAJw7A0P64NaF7uOlF8hJBD+W6xRsXYm88PsMVAAcYprHU9qbgxlS/HpV4bBeO9x76AQUZDYMNCyAAznu39kL8Rh+BTbSMMt+UshFSGFnxEoeuJq3K/3gszPS3E=
  skip_cleanup: true
  bucket: opengrid.io
  region: us-west-2
  on:
    repo: Chicago/opengrid
    branch: opengrid.io