language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script:
  - bundle exec htmlproofer index.html --only-4xx --check-html
env:
- global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: s3
  access_key_id: AKIAJODHIGA544MQYMNA
  secret_access_key:
    secure: j+5KV/GnQ2K+eCbuiUdYsBbYPPMOJopIqBYg6xsR+viRwlb/2nYEGNshpeK4CGCL6dgj16eYyGos/GKj2MJSpVPNe26fpBk37hhZzRu4ycq+CIa4nWyJhaHyw9Bn3aJbnD9mdSwBxXJ9WObIK06YhpbjQpKB3DQYHNbuk99Lus/ZSpCZvHq5IKhSLhZoJCi6EQEAv9ZPQ86CeukeKawmGfW5veKXfzyyjaomlfd3i25u7uES4YRdJsLKVJEzGBAXrpbeqttSWV549SP+c+kJsrI4ysiwmguyFBty/SAaNRLDXXsfBJ6ptiNaFz29CcjXCQRNWxjr8vi6tPGcTiY1sgSviT4uGQukTugcW3NhgBTD5yRrJNw3tK+z1JqCj0g1nJScwg5ELu4HENCTcFul5y131zvAzBvUaP/qcoGUU8YVQvrFbaBkpvxK3XJpP0TVv3tXXZjzRg7JEEBaTqqw+ear2Zeywtot9fWv3jLIYserLhtYuRLQ91VOiE+vMyP58hXP+jZTtxEDrBkgRWmes2wakGyxHUHmYy9u79G1lxQDodSmgAJw7A0P64NaF7uOlF8hJBD+W6xRsXYm88PsMVAAcYprHU9qbgxlS/HpV4bBeO9x76AQUZDYMNCyAAznu39kL8Rh+BTbSMMt+UshFSGFnxEoeuJq3K/3gszPS3E=
  skip_cleanup: true
  bucket: opengrid.io
  region: us-west-2
  on:
    repo: Chicago/opengrid
    branch: opengrid.io