language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script:
  - bundle exec htmlproofer index.html --only-4xx --check-html
env:
- global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: never
    on_failure: never