# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "0.12"

platform:
  - x86
  - x64

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails
  
install:
  # install modules
  - npm install -g gulp
  - npm install
  
build_script:
  - gulp release

# to disable deployment
deploy: off

notifications:
  # Email
  - provider: Email
    to:
      - rladines@eki-consulting.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true  
