# version format
version: 1.0.0

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012	

# scripts that are called at very beginning, before repo cloning
init:
#noop  
  
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails

# scripts that run after cloning repository
install:
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#  
  
# to run your custom scripts instead of automatic MSBuild
build_script:
  - gulp release

# to disable deployment
deploy: off


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Email
  - provider: Email
    to:
      - rladines@eki-consulting.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true  
