site_name: OpenGrid
site_url: http://www.opengrid.io
site_description: Explore your space with OpenGrid
site_author: City of Chicago

repo_url: https://github.com/Chicago/opengrid
theme: readthedocs

pages:
- Home: index.md
#- User Guide:
#   - End-user documentation: User Documentation.md
#- System administration:
#     - App Architecture: Architecture.md
#     - Installation and Setup: Installation and Setup.md
#     - Build Procedures: Build Procedures.md
#     - Configuration: OpenGrid Configuration.md
#    - Administration: Administration.md
- OpenGrid Layout:
        - Launch Screen: layout/launch-screen.md
        - Table Grid: layout/table-grid.md
- Finding Data:
        - Getting Started: finding-data/getting-started.md
        - Advanced Filtering: finding-data/advanced-filtering.md
        - Automatically Refresh Searches: finding-data/auto-refresh-search.md
        - Commonly Used Queries: finding-data/commonly-used-queries.md
        - Searching With Relative Time: finding-data/relative-time-searches.md
- Search by Location:
        - Within An Area: search-location/within-geospatial-filter.md
        - Near A Location: search-location/near-geospatial-filter.md
- Customize the Look: customize-look/index.md
- Charts and Heatmaps:
        - Heatmaps: charts-heatmaps/heatmaps.md
        - Tile map: charts-heatmaps/tile-map.md
- Map Layers: map-layers/index.md
- Measure Distance: measure-distances/index.md
- Developers:
    - API: OpenGrid-API.md
- System administration:
    - App Architecture: Architecture.md
    - Installation and Setup: Installation-and-Setup.md
    - Build Procedures: Build-Procedures.md
    - Configuration: OpenGrid-Configuration.md
     
markdown_extensions:
    - toc:
        permalink: 
    - admonition:





copyright: Copyright &copy; 2015-2016 <a href="http://www.cityofchicago.org">City of Chicago</a> and licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a>.
